// packages/@streamjar/ui-ng/demo/app/demo/demo.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { ITable } from '../table/table.component';

export interface IDemoConfig {
    docs?: ITable[] | { [key: string]: ITable[] },
    name: string;
    component: string;

    html?: string;
    ts?: string;
    scss?: string;
}

export enum DemoContent {
    HTML,
    SCSS,
    TS,
}

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
    selector: 'demo',
    styleUrls: ['../common.scss'],
    templateUrl: './demo.component.html'
})
export class DemoComponent {
    public DemoContent = DemoContent;
    public config: IDemoConfig;
    public show: DemoContent = DemoContent.HTML;

    public htmlOpts = {theme: 'vs-dark', language: 'html'};
    public tsOpts = {theme: 'vs-dark', language: 'typescript'};
	public scssOpts = {theme: 'vs-dark', language: 'scss'};

	public tabs: string[] = [];
	public docs: string = '';

    @Input('config')
    public set _config(config: IDemoConfig) {
        this.config = {
            ...config,
            html: config.html && config.html.trim(),
            ts: config.ts && config.ts.trim(),
            scss: config.scss && config.scss.trim(),
        }

		this.show = config.html ? DemoContent.HTML : config.scss ? DemoContent.SCSS : DemoContent.TS;

		if (this.config.docs && (<ITable[]>this.config.docs).length) {
			const ref = <ITable[]>this.config.docs;

			this.config.docs = { [this.config.component]: ref };
		}


		this.tabs = Object.keys(this.config.docs || {});
		this.docs = this.tabs[0];
    }

}

<ng-container *ngIf="config">
    <h2 class="demo__name"> {{ config.name }} </h2>

    <div class="demo__section">
        <h5> Example </h5>

        <ng-content></ng-content>
    </div>

    <div class="demo__section" *ngIf="tabs.length">
        <h5> Documentation </h5>

		<jar-tabs (selected)="docs = $event">
			<jar-tab *ngFor="let tab of tabs" [value]="tab"> {{tab}} </jar-tab>
		</jar-tabs>

		<ng-container *ngIf="docs">
			<demo-table [name]="docs" [docs]="config.docs[docs]"></demo-table>
		</ng-container>
    </div>

    <div class="demo__section" *ngIf="config.html || config.scss || config.ts">
        <h5> Code </h5>

        <jar-tabs (selected)="show = $event">
            <jar-tab [value]="DemoContent.HTML" *ngIf="config.html">HTML</jar-tab>
            <jar-tab [value]="DemoContent.TS" *ngIf="config.ts">TS</jar-tab>
            <jar-tab [value]="DemoContent.SCSS" *ngIf="config.scss">SCSS</jar-tab>
        </jar-tabs>

        <ngx-monaco-editor *ngIf="show === DemoContent.HTML" [options]="htmlOpts" [(ngModel)]="config.html"></ngx-monaco-editor>
        <ngx-monaco-editor *ngIf="show === DemoContent.SCSS" [options]="scssOpts" [(ngModel)]="config.scss"></ngx-monaco-editor>
        <ngx-monaco-editor *ngIf="show === DemoContent.TS" [options]="tsOpts" [(ngModel)]="config.ts"></ngx-monaco-editor>
    </div>
</ng-container>

// packages/@streamjar/ui-react/demo/src/demo/demo.tsx
import * as React from 'react';
import MonacoEditor from 'react-monaco-editor';

import './demo.scss';

export interface IDemoConfig {
	name: string;
	components: IDemoComponent[];
	examples: string;
}

export interface IDemoComponent {
	name: string;
	props: IDemoProp[];
}

export interface IDemoProp {
	name: string;
	default: string | number;
	type: string;
	description: string;
}
export interface IDemoProps {
	config: IDemoConfig;
}

export class Demo extends React.PureComponent<IDemoProps> {
	public render() {
		const { name, components, examples } = this.props.config;

		const docs = (
			<div className="demo__section">
				<h5> Documentation </h5>
				{components.map(component =>  this.getTable(component))}
			</div>
		);

		return (
			<div>
				<h2 className="demo__name"> {name} </h2>

				<div className="demo__section">
					<h5> Example </h5>

					{this.props.children}
				</div>

				{!!components.length && docs}

				<div className="demo__section">
					<h5> Code </h5>
					<MonacoEditor
						height={600}
						theme="vs-dark"
						language="typescript"
						options={{ autoIndent: true }}
						value={examples.trim()}
						/>
				</div>
			</div>
		);
	}

	private getTable(component: IDemoComponent): JSX.Element {
		return (
			<div key={component.name}>
				<p className="elementName"> Element Name: <code> {component.name} </code> </p>
				<table className="table">
					<thead>
						<tr>
							<th className="table__name"> Name </th>
							<th className="table__default"> Default</th>
							<th className="table__intype"> Type</th>
							<th className="table__desc"> Description</th>
						</tr>
					</thead>

					<tbody>
						{component.props.map(prop => this.getPropRow(prop))}
					</tbody>
				</table>
			</div>
		);
	}

	private getPropRow(prop: IDemoProp): JSX.Element {
		return (
			<tr key={prop.name}>
				<td className="table__name"> {prop.name} </td>
				<td className="table__default"> {prop.default} </td>
				<td className="table__intype"> {prop.type} </td>
				<td className="table__desc"> {prop.description} </td>
			</tr>
		);
	}
}
