// packages/@streamjar/ui-ng/src/lib/section/section.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'jar-section',
	templateUrl: './section.component.html',
})
export class SectionComponent {
	public hasTabs: boolean;
	public onlyShowTabs = false;

	@Input('only-tabs')
	public set onlyTabs(tabs) {
		this.onlyShowTabs = tabs !== false;
	}

	@Input()
	public set tabs(tabs) {
		this.hasTabs = tabs !== false;
	}
}

<div class="jar-section" ngStyle.xs="padding: 0; margin: 10px;">
	<div [fxLayout]="onlyShowTabs ? 'row-reverse' : 'row'" [fxLayout.xs]="onlyShowTabs ? 'column-reverse' : 'column'" class="jar-section__header" fxLayoutAlign="flex-end center" [class.jar-section__tabs]="hasTabs">
		<h2 class="jar-section__title">
			<ng-content select=".jar-section-header"></ng-content>
		</h2>
		<span fxFlex></span>
		<ng-content select=".jar-section-action"></ng-content>
	</div>
	<div class="jar-section__content">
		<ng-content select=".jar-section-content"></ng-content>
	</div>
</div>

// packages/@streamjar/ui-react/src/layouts/section/Section.tsx
import * as React from 'react';
import * as classnames from 'classnames';

export interface ISectionProps {
	/** Header component */
	header?: JSX.Element;

	/** an action to display */
	action?: JSX.Element;

	/** Whether the action is tabs */
	tabs?: boolean;

	/** Whether we are only displaying tabs */
	onlyTabs?: boolean;
}

/** Display a section */
export const Section = (props: React.PropsWithChildren<ISectionProps>) => {
	const { tabs, onlyTabs, header, action, children } = props;

	const className = classnames({
		'jar-section__header': true,
		'jar-section__tabs': tabs,
		'layout-align-end-center': true,
		'layout-column-reverse.xs': onlyTabs,
		'layout-column.xs': !onlyTabs,
		'layout-row': !onlyTabs,
		'layout-row-reverse': onlyTabs,
	});

	return (
		<div className="jar-section">
			<div className={className}>
				<h2 className="jar-section__title">
					{header && <div className="jar-section-header" style={{ padding: onlyTabs ? 0 : undefined }}> {header} </div>}
				</h2>
				<span className="flex"></span>
				{action && <div className="jar-section-action"> {action} </div>}
			</div>
			<div className="jar-section__content">
				{children}
			</div>
		</div>
	);
};
