// packages/@streamjar/ui-ng/src/lib/avatar/avatar.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

import { GravatarService } from './gravatar.service';

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'jar-avatar',
	styles: [`:host { display: inline-flex; }`],
	template: '<img class="jar-avatar" [src]="url$ | async" [style.width]="size + \'px\'" [style.height]="size + \'px\'" />',
})
export class JarAvatarComponent {
	public url$ = new BehaviorSubject('/assets/noavatar.png');

	@Input()
	public size = 60;

	@Input()
	set data(data: string | { avatar?: string; email?: string; }) {
		if (!data || data === 'null') {
			return;
		}

		if (typeof data === 'object') {
			if (data.avatar) {
				this.url$.next(data.avatar);
			} else if (data.email) {
				this.url$.next(this.gravatar.parse(data.email));
			}
		} else {
			this.url$.next(data);
		}
	}

	constructor(private gravatar: GravatarService) { }
}

// packages/@streamjar/ui-react/src/components/avatar/Avatar.tsx
import * as React from 'react';
import { Md5 } from 'ts-md5';

export type IAvatarValue = string | { email?: string; avatar?: string } | undefined;

export interface IAvatarProps {
	size?: number;
	data?: IAvatarValue;
}

export const getGravatar = (email: string): string => {
	return `https://www.gravatar.com/avatar/${Md5.hashStr(email)}`;
};

export function fetchAvatar(data: IAvatarValue): string {
	if (typeof data === 'object') {
		if (data.avatar) {
			return data.avatar;
		} else if (data.email) {
			return getGravatar(data.email);
		}
	} else if (typeof data === 'string') {
		return data;
	}

	return '/assets/noavatar.png';
}

export const Avatar: React.FC<IAvatarProps> = ({ size = 60 , data }: IAvatarProps) => {
	const avatar: string = fetchAvatar(data);

	return (
		<div className="jar-avatar-container" style={{ display: 'inline-flex' }}>
			<img alt="Avatar" className="jar-avatar" src={avatar} width={`${size}px`} height={`${size}px`} />
		</div>
	);
};
