// packages/@streamjar/ui-ng/src/lib/popup/popup.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'jar-popup',
	templateUrl: './popup.component.html',
})
export class PopupComponent {
	@Input()
	public title = '';

	@Input()
	public tag: string;
}

<div class="jar-popup" fxLayout="row" fxLayoutAlign="center center">
	<div class="jar-popup__container" fxLayout="column" fxLayoutAlign="flex-start">
		<h2 class="jar-logo" *ngIf="title === ''"><img src="/assets/jar-white.svg" /></h2>
		<h2 *ngIf="title !== ''"> {{ title }} </h2>
		<p class="jar-popup-tagline"> {{ tag }} </p>
		<ng-content></ng-content>
	</div>
</div>

// packages/@streamjar/ui-react/src/layouts/popup/Popup.tsx
import * as React from 'react';

export interface IPopupProps {
	/** Title of the element */
	title?: string;

	/** Tagline of the element */
	tag?: string;
}

export const Popup: React.FC<IPopupProps> = (props: React.PropsWithChildren<IPopupProps>) => {
	const { children, tag, title } = props;

	return (
		<div className="jar-popup layout-row layout-align-center-center">
			<div className="jar-popup__container j-dark layout-column layout-align-start-start">
				{title === '' && <h2 className="jar-logo"><img src="/assets/jar-white.svg" alt="StreamJar" /></h2>}
				{title !== '' && <h2> {title} </h2>}

				<p className="jar-popup-tagline"> {tag} </p>

				{children}
			</div>
		</div>
	);
};

Popup.defaultProps = {
	title: '',
};
