// packages/@streamjar/ui-ng/src/lib/card/card.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'jar-card',
	templateUrl: './card.component.html',
})
export class CardComponent {
	@Input()
	public icon: string;
}

<div class="jar-card" fxLayout="column">
	<div class="jar-card__inner" fxLayout="row" fxLayout.xs="column" fxLayoutAlign="start center">
		<jar-avatar class="jar-card__avatar" *ngIf="icon" [data]="icon" size="50" ngClass.xs="smallAvatar"></jar-avatar>

		<div class="jar-card__content" fxFlex>
		    <ng-content select=".jar-card-content"></ng-content>
		</div>
	</div>

	<div class="jar-card-footer" fxLayout="row" fxLayoutAlign="end center">
	    <ng-content select=".jar-card-actions"></ng-content>
	</div>
</div>

// packages/@streamjar/ui-react/src/lib/card/card.tsx
import * as React from 'react';

import { Avatar, AvatarValue } from '../avatar';

export interface ICardContentProps {
	icon?: AvatarValue;
}

export class Card extends React.PureComponent {
	public render(): JSX.Element {
		const { children } = this.props;

		return (
			<div className="jar-card layout-column">
				{children}
			</div>
		);
	}
}

export class CardContent extends React.PureComponent<ICardContentProps> {
	public render(): JSX.Element {
		const { children, icon } = this.props;

		return (
			<div className="jar-card__inner layout-row layout-align-start-center layout-column-xs layout-align-center-center-xs">
				{icon && <div className="jar-card__avatar"><Avatar data={icon} size={50}></Avatar></div>}

				<div className="jar-card__content flex">
					{children}
				</div>
			</div>
		);
	}
}

export class CardActions extends React.PureComponent {
	public render(): JSX.Element {
		const { children } = this.props;

		return (
			<div className="jar-card-footer layout-row layout-align-end-center layout-column-xs">
				{children}
			</div>
		);
	}
}
