// packages/@streamjar/ui-react/src/lib/spinner/spinner.tsx
import * as React from 'react';

export interface ISpinnerProps {
	size?: number;
}

export class Spinner extends React.PureComponent<ISpinnerProps> {
	public static defaultProps: Partial<ISpinnerProps> = {
		size: 50,
	};

	constructor(props: ISpinnerProps) {
		super(props);
	}

	public render(): JSX.Element {
		const { size } = this.props;

		return (
			<div className="jar-spinner-outer" style={{ width: `${size}px`, height: `${size}px`}}>
				<div className="jar-spinner" style={{ width: `${size}px`, height: `${size}px`}}>
					<svg className="jar-spinner__container" viewBox="25 25 50 50">
						<circle className="jar-spinner__path" cx="50" cy="50" r="20" fill="none" strokeWidth="3" strokeMiterlimit="10" />
					</svg>
				</div>
			</div>
		);
	}
}

// packages/@streamjar/ui-ng/src/lib/spinner/spinner.component.ts
import {
	Component,
	HostBinding,
	Input,
	ChangeDetectionStrategy,
} from '@angular/core';

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'jar-spinner',
	styles: [`:host { display: block; margin: 0 auto; }`],
	templateUrl: './spinner.component.html',

})
export class JarSpinnerComponent {
	@HostBinding('style.width')
	@HostBinding('style.height')
	public dimensions = '50px';

	@Input()
	set size(size: number) {
		this.dimensions = `${size}px`;
	}
}

<div class="jar-spinner" [style.width]="dimensions" [style.height]="dimensions">
	<svg class="jar-spinner__container" viewBox="25 25 50 50">
		<circle class="jar-spinner__path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10"/>
	</svg>
</div>
