// packages/@streamjar/ui-ng/src/lib/platforms/platforms.component.ts
import { forwardRef, ChangeDetectionStrategy, ChangeDetectorRef, Component, OnDestroy, OnInit, Input } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { BehaviorSubject, Subscription } from 'rxjs';
import { skip } from 'rxjs/operators';

export const JAR_CHECKBOX_CONTROL_VALUE_ACCESSOR: any = {
	multi: true,
	provide: NG_VALUE_ACCESSOR,
	useExisting: forwardRef(() => PlatformsComponent),
};

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	providers: [JAR_CHECKBOX_CONTROL_VALUE_ACCESSOR],
	selector: 'jar-platforms',
	templateUrl: './platforms.component.html',
})
export class PlatformsComponent implements ControlValueAccessor, OnInit, OnDestroy {
	public static platforms = ['mixer', 'twitch', 'smashcast', 'dlive', 'picarto']
	public all$ = new BehaviorSubject(true);
	public value$ = new BehaviorSubject([...PlatformsComponent.platforms]);
	public remainingCount = 0;
	public subscriptions: Subscription[] = [];

	@Input()
	public supported = PlatformsComponent.platforms;

	private onChange = (val?: boolean) => undefined;
	private onTouch = (val?: boolean) => undefined;

	constructor(private cd: ChangeDetectorRef) {
	}

	public ngOnInit(): void {
		this.value$.next(this.supported);

		this.subscriptions.push(this.all$.pipe(skip(1)).subscribe(val => {
			if (val === true) {
				this.setValue([...this.supported]);
			}
		}));

		this.subscriptions.push(this.value$.subscribe(val => {
			this.remainingCount = (val || []).length

			this.cd.detectChanges();
		}));
	}

	public ngOnDestroy(): void {
		this.subscriptions.forEach(sub => sub.unsubscribe());
	}

	public setValue(value: any): void {
		this.value$.next(value);
		this.onChange(value);
	}

	public writeValue(obj: any): void {
		if (!obj) {
			this.setValue([...this.supported]);

			return;
		}

		this.value$.next(obj);
	}

	public registerOnChange(fn: any): void {
		this.onChange = fn;
	}

	public registerOnTouched(fn: any): void {
		this.onTouch = fn;
	}

	public toggle(name: string): void {
		if (this.all$.getValue()) {
			return;
		}

		if (this.value$.getValue().indexOf(name) !== -1) {
			this.setValue(this.value$.getValue().filter(a => a !== name));
		} else {
			this.setValue([...this.value$.getValue(), name]);
		}
	}

	public dismissAll(): void {
		if (this.all$.getValue()) {
			this.all$.next(false);
		}
	}
}

<jar-checkbox [ngModel]="all$ | async" (ngModelChange)="all$.next($event)" colour="accent"> All </jar-checkbox>
<hr style="border: 1px solid rgb(105, 76, 127)" />
<div [style.opacity]="(all$ | async) ? .5 : 1">
	<jar-checkbox *ngIf="supported.includes('mixer')" (click)="dismissAll()" [disabled]="((value$ | async).includes('mixer') && remainingCount === 1)" [ngModel]="(value$ | async).includes('mixer')" (ngModelChange)="toggle('mixer')" colour="platform-mixer"> Mixer </jar-checkbox>
	<jar-checkbox *ngIf="supported.includes('twitch')" (click)="dismissAll()" [disabled]="((value$ | async).includes('twitch') && remainingCount === 1)" [ngModel]="(value$ | async).includes('twitch')" (ngModelChange)="toggle('twitch')" colour="platform-twitch"> Twitch </jar-checkbox>
	<jar-checkbox *ngIf="supported.includes('smashcast')" (click)="dismissAll()" [disabled]="((value$ | async).includes('smashcast') && remainingCount === 1)" [ngModel]="(value$ | async).includes('smashcast')" (ngModelChange)="toggle('smashcast')" colour="platform-smashcast"> Smashcast </jar-checkbox>
	<jar-checkbox *ngIf="supported.includes('dlive')" (click)="dismissAll()" [disabled]="((value$ | async).includes('dlive') && remainingCount === 1)" [ngModel]="(value$ | async).includes('dlive')" (ngModelChange)="toggle('dlive')" colour="platform-dlive"> DLive </jar-checkbox>
	<jar-checkbox *ngIf="supported.includes('picarto')" (click)="dismissAll()" [disabled]="((value$ | async).includes('picarto') && remainingCount === 1)" [ngModel]="(value$ | async).includes('picarto')" (ngModelChange)="toggle('picarto')" colour="platform-picarto"> Picarto </jar-checkbox>
</div>

// packages/@streamjar/ui-react/src/lib/platforms/platforms.tsx
import * as React from 'react';

import { Checkbox } from '../checkbox';

export interface IPlatformsProps {
	supported?: string[];
	value?: string[];
	onChange(platforms: string[]): void;
}

export interface IPlatformsState {
	value: string[];
	all: boolean;
}

export class Platforms extends React.PureComponent<IPlatformsProps, IPlatformsState> {
	public static defaultProps: Partial<IPlatformsProps> = {
		onChange: () => { /* */ },
		supported: ['mixer', 'twitch', 'smashcast', 'dlive', 'picarto'],
	};

	constructor(props: IPlatformsProps) {
		super(props);

		this.state = this.handleProps();
	}

	public componentDidUpdate(prev: IPlatformsProps): void  {
		if (prev.value !== this.props.value) {
			this.setState(this.handleProps());
		}
	}

	public onChecked(type: string, value: boolean): void {
		this.setState(state => {
			let val = { value: [...state.value, type] };

			if (state.value.includes(type)) {
				val = { value: state.value.filter(i => i !== type) };
			}

			this.props.onChange(val.value);

			return val;
		});
	}

	public disableAll = (value: boolean = false): void => {
		if (!value) {
			this.setState({ all: false });
		} else {
			this.props.onChange(this.props.supported!);

			this.setState({
				all: true,
				value: this.props.supported!,
			});
		}
	}

	public disableAllFalse = (): void => {
		this.disableAll(false);
	}

	public render(): JSX.Element {
		const { supported } = this.props;
		const { all } = this.state;

		return (
			<React.Fragment>
				<Checkbox value={all} onChange={this.disableAll} colour="accent"> All </Checkbox>
				<hr style={{ border: '1px solid rgb(105, 76, 127)'}} />
				<div style={{ opacity: all ? 0.2 : 1 }}>
					{supported!.includes('mixer') && this.getPlatform('mixer', 'Mixer')}
					{supported!.includes('twitch') && this.getPlatform('twitch', 'Twitch')}
					{supported!.includes('smashcast') && this.getPlatform('smashcast', 'Smashcast')}
					{supported!.includes('dlive') && this.getPlatform('dlive', 'DLive')}
					{supported!.includes('picarto') && this.getPlatform('picarto', 'Picarto')}
				</div>
			</React.Fragment>
		);
	}

	private getPlatform(id: string, name: string): JSX.Element {
		const { value } = this.state;
		const last = value.length === 1;

		return (
			<div onClick={this.disableAllFalse}>
				<Checkbox
					value={value.includes(id)}
					colour={`platform-${id}`}
					onChange={this.onChecked.bind(this, id)} // tslint:disable-line
					disabled={value.includes(id) && last}>
					{name}
				</Checkbox>
			</div>
		);
	}

	private handleProps(): IPlatformsState {
		if (this.props.value) {
			const val = this.props.value.filter(i => this.props.supported!.indexOf(i) !== -1);

			return { value: val, all: val.length === this.props.supported!.length };
		} else {
			return { value: this.props.supported!, all: true };
		}
	}
}
