// packages/@streamjar/ui-react/src/lib/dialog/dialog.tsx
import * as React from 'react';

import { Portal } from '../outlet/portal';
import { Button } from '../button';
import { Transition } from 'react-transition-group';
import { Spinner } from '../spinner';

// tslint:disable max-classes-per-file

export interface IDialogHeaderProps {
	onClose?(): void;
}

export class DialogHeader extends React.PureComponent<IDialogHeaderProps> {
	public static defaultProps = {
		onClose: () => { /* */ },
	};

	public render(): JSX.Element {
		const { children, onClose } = this.props;

		return (
			<div className="jar-dialog-header" style={{ flexShrink: 0 }}>
				<h5 className="jar-dialog-header__title layout-row layout-align-between-center">
					{children}
				</h5>

				<span className="flex"></span>

				<Button round={true} raised={true} icon="close" onClick={onClose}></Button>
			</div>
		);

	}
}

export class DialogContent extends React.PureComponent {
	public render(): JSX.Element {
		const { children } = this.props;

		return (
			<div style={{ flex: 1, padding: '15px 25px 10px', overflow: 'auto' }}>
				{children}
			</div>
		);
	}
}

export class DialogFooter extends React.PureComponent {
	public render(): JSX.Element {
		const { children } = this.props;

		return (
			<div className="layout-row layout-align-end-center" style={{ padding: '20px 25px' }}>
				{children}
			</div>
		);
	}
}

export interface IDialogProps {
	state?: object;
	show: boolean;
	onClose(data: object | null): void;
}

export interface IDialogConfig {
	width?: string;
	height?: string;
	minWidth?: string;
	maxWidth?: string;
	state: DialogStatus;
}

export enum DialogStatus {
	LOADING,
	LOADED,
}

export interface IDialogState {
	jarDialog: IDialogConfig;
	jarOpen: boolean;
}

const ANIMATION = 400;

const DEFAULT: React.CSSProperties = {
	transform: 'translateY(25%) scale(0.9)',
	transition: `${ANIMATION}ms cubic-bezier(0.25, 0.8, 0.25, 1)`,
};

const CLASSES: { [key: string]: React.CSSProperties} = {
	entered: { transform: 'translateY(0) scale(1)' },
	entering: { transform: 'translateY(0) scale(0.9)' },
	exiting: { transform: 'translateY(0) scale(0.9)' },
};

const OVERLAY_BASE: React.CSSProperties = {
	opacity: 0,
	transition: `${ANIMATION}ms cubic-bezier(0.25, 0.8, 0.25, 1)`,
};

const OVERLAY_CLASSES: { [key: string]: React.CSSProperties} = {
	entered: { opacity: 1},
	entering: { opacity: 1 },
	exiting: { opacity: 0 },
};

export abstract class BaseDialog<P = {}, S = {}> extends React.PureComponent<IDialogProps & P, IDialogState & S> {
	public initState?: DialogStatus;

	constructor(props: IDialogProps & P) {
		super(props);

		this.closeBackdrop = this.closeBackdrop.bind(this);
		this.getDialog = this.getDialog.bind(this);
	}

	public abstract initialState(): S;

	public dialogDidOpen() { /* */ }
	public dialogWillClose()  { /* */ }

	public componentDidUpdate(prev: IDialogProps & P) {
		if (prev.show !== this.props.show) {
			this.setState({
				jarOpen: this.props.show,
			});

			if (this.props.show) {
				this.dialogDidOpen();
			}
		}
	}

	public loading(): void {
		this.setState(state => ({
			jarDialog: {
				...(state.jarDialog as any),
				state: DialogStatus.LOADED,
			},
		}));
	}

	public loaded() {
		this.setState(state => ({
			jarDialog: {
				...(state.jarDialog as any),
				state: DialogStatus.LOADED,
			},
		}));
	}

	public setupDialog(data: IDialogConfig): void {
		if (this.state !== undefined) {
			console.error('Calls to setupDialog() are forbidden post-init');
		}

		this.initState = data.state;

		this.state = { jarOpen: this.props.show || false, jarDialog: data, ...(this.initialState() as any)};
	}

	public close(data: object | null = null): void {
		if (!this.state.jarOpen) {
			return;
		}

		this.setState({
			jarOpen: false,
		});

		this.dialogWillClose();

		this.setState(state => ({
			jarDialog: {
				...(state.jarDialog as any),
				state: this.initState,
			},
			...(this.initialState() as any),
		}));

		setTimeout(() => {

			this.props.onClose(data);
		},         ANIMATION);
	}

	public closeBackdrop(event: React.SyntheticEvent<HTMLDivElement>): void {
		if (event.currentTarget === event.target) {
			this.close(null);
		}
	}

	public render(): JSX.Element {
		const { jarOpen } = this.state;

		return (
			<Transition in={jarOpen} appear={true} unmountOnExit={true} timeout={{ exit: 200, enter: 0}} children={this.getDialog} />
		);
	}

	public getDialog(state: string): JSX.Element {
		if (this.props.show === false) {
			return <React.Fragment />;
		}

		const { jarDialog } = this.state;

		let dialog = this.renderDialog();

		// we could use a provider here.. ooooor we could mutate some childs children. sorry.
		if (dialog.type === React.Fragment) {
			const childProps = React.Children.map(dialog.props.children, (child: any) => {
				if (child.type !== DialogHeader) {
					return child;
				}

				return React.cloneElement(child, { ...child.props, onClose: () => { this.close(null); } });
			});

			dialog = React.cloneElement(dialog, { children: childProps });
		}

		const overlay = (
			<div className="jar-dialog__overlay layout-row layout-align-center-center">
				<Spinner size={40} />
			</div>
		);

		return (
			<Portal>
				<div className="jar-dialog-target" style={{position: 'relative', zIndex: 10000 }}>
					<div className="jar-overlay layout-column layout-align-center-center"
						onClick={this.closeBackdrop}
						style={{...OVERLAY_BASE, ...OVERLAY_CLASSES[state]}}>
						<div className="jar-dialog layout-column" style={{...(jarDialog as any), ...DEFAULT, ...CLASSES[state]}}>
							{jarDialog.state === DialogStatus.LOADING && overlay}

							{dialog}
						</div>
					</div>
				</div>
			</Portal>
		);
	}

	protected abstract renderDialog(): JSX.Element;
}

// packages/@streamjar/ui-ng/src/lib/dialog/dialog.component.ts
import {
	animate,
	state,
	style,
	transition,
	trigger,
} from '@angular/animations';
import {
	Component,
	Input,
	ViewEncapsulation,
	ChangeDetectionStrategy,
} from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { take } from 'rxjs/operators';

import { DialogRefService } from './dialogRef.service';

const ANIMATION_DURATION = 400;

export enum LoadingState {
	LOADED,
	LOADING,
}

@Component({
	animations: [
		trigger('dialogAnimation', [
			state('void', style({ transform: 'translateY(25%) scale(0.9)' })),
			state('enter', style({ transform: 'translateY(0%) scale(1)' })),
			state('exit', style({ transform: 'translateY(25%)' })),
			transition('* => *', animate(`${ANIMATION_DURATION}ms cubic-bezier(0.25, 0.8, 0.25, 1)`)),
		]),

		trigger('overlay', [
			state('void', style({ opacity: 0 })),
			state('enter', style({ opacity: 1 })),
			state('exit', style({ opacity: 0 })),
			transition('* => *', animate(`${ANIMATION_DURATION}ms cubic-bezier(0.25, 0.8, 0.25, 1)`)),
		]),
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'jar-dialog',
	styles: [`:host { position: relative; z-index: 10000; }`],
	templateUrl: './dialog.component.html',
})
export class JarDialogComponent {
	public LoadingState = LoadingState;

	public loadingState$ = new BehaviorSubject<LoadingState>(LoadingState.LOADED);

	@Input()
	public height: string;

	@Input()
	public width: string;

	@Input()
	public maxWidth: string;

	@Input()
	public minWidth: string;

	public state = 'enter';

	constructor(private dialog: DialogRefService) {
		dialog.onClose.pipe(take(1)).subscribe((data) => {
			this.dismiss(null, data);
		});
	}

	public dismiss(event, data = null): void {
		if (!event || event.currentTarget === event.target) {
			this.state = 'exit';

			setTimeout(() => {
				this.dialog.onClosed.next(data);
				this.dialog.onClosed.complete();
			}, ANIMATION_DURATION);
		}
	}
}

@Component({
	animations: [
		trigger('dialogAnimation', [
			state('void', style({ transform: 'translateY(25%) scale(0.9)' })),
			state('enter', style({ transform: 'translateY(0%) scale(1)' })),
			state('exit', style({ transform: 'translateY(25%)' })),
			transition('* => *', animate(`${ANIMATION_DURATION}ms cubic-bezier(0.25, 0.8, 0.25, 1)`)),
		]),

		trigger('overlay', [
			state('void', style({ opacity: 0 })),
			state('enter', style({ opacity: 1 })),
			state('exit', style({ opacity: 0 })),
			transition('* => *', animate(`${ANIMATION_DURATION}ms cubic-bezier(0.25, 0.8, 0.25, 1)`)),
		]),
	],
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'jar-dialog-loading',
	styles: [`:host { position: relative; z-index: 10000; }`],
	templateUrl: './dialog.component.html',
})
export class JarDialogLoadableComponent {
	public LoadingState = LoadingState;

	public loadingState$ = new BehaviorSubject<LoadingState>(LoadingState.LOADING);

	@Input()
	public height: string;

	@Input()
	public width: string;

	@Input()
	public maxWidth: string;

	@Input()
	public minWidth: string;

	public state = 'enter';

	constructor(private dialog: DialogRefService) {
		dialog.onClose.pipe(take(1)).subscribe((data) => {
			this.dismiss(null, data);
		});
	}

	public loaded(): void {
		this.loadingState$.next(LoadingState.LOADED);
	}

	public fetching(): void {
		this.loadingState$.next(LoadingState.LOADING);
	}

	public dismiss(event, data = null): void {
		if (!event || event.currentTarget === event.target) {
			this.state = 'exit';

			setTimeout(() => {
				this.dialog.onClosed.next(data);
				this.dialog.onClosed.complete();
			}, ANIMATION_DURATION);
		}
	}
}

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'jar-dialog-header',
	styles: [':host { flex-shrink: 0; }'],
	template: '<h5 class="jar-dialog-header__title"><ng-content></ng-content></h5>' +
		'<span fxFlex></span>' +
		'<button type="button" jarBtn round icon="close" (click)="dialog.close()"></button>',
})
export class JarDialogHeaderComponent {
	constructor(public dialog: DialogRefService) {}

}

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'jar-dialog-content',
	styles: [':host { flex: 1; padding: 15px 25px 10px; overflow: auto; }'],
	template: '<div fxFlex><ng-content></ng-content></div>',
})
export class JarDialogContentComponent {
}

@Component({
	changeDetection: ChangeDetectionStrategy.OnPush,
	selector: 'jar-dialog-footer',
	styles: [':host { display: flex; flex-direction: row; align-items: flex-end; padding: 20px 25px; }'],
	template: '<ng-content></ng-content>',
})
export class JarDialogActionsComponent {

}

<div class="jar-overlay" (click)="dismiss($event)" fxLayout="column" fxLayoutAlign="center center" [@overlay]="state">
	<div class="jar-dialog" fxLayout="column" [@dialogAnimation]="state" [style.min-width]="minWidth" [style.max-width]="maxWidth" [style.width]="width" [style.height]="height">
		<div class="jar-dialog__overlay" fxLayout="row" fxLayoutAlign="center center" *ngIf="(loadingState$ | async) === LoadingState.LOADED">
			<jar-spinner size="40"></jar-spinner>
		</div>

		<ng-content select="jar-dialog-header"></ng-content>
		<ng-content select="jar-dialog-content"></ng-content>
		<ng-content select="jar-dialog-footer"></ng-content>
	</div>
</div>
